// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
