// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort():Promise<number>;

export function GetVersion():Promise<string>;

export function OpenFileDialog():Promise<string>;
